'use client'

import React, { useState, useEffect, useRef, useCallback } from 'react'
import { 
  Shield, Activity, Brain, LineChart, AlertTriangle, CheckCircle2, 
  Search, Filter, TrendingUp, TrendingDown, Minus, Eye, MessageSquare,
  BarChart3, PieChart, Zap, Globe, Lock, Bot, Users, Target,
  ArrowRight, Play, Pause, RefreshCw, Download, Settings, Bell,
  ChevronRight, ChevronDown, ChevronUp, Star, Clock, MapPin, Building2,
  Package, Truck, Factory, Database, Cpu, Wifi, Radio, Mail, Phone,
  Send, X, Plus, Edit3, Trash2, Save, Calendar, FileText, Scale,
  Gavel, ClipboardCheck, Fingerprint, ShieldCheck, AlertCircle,
  Info, ExternalLink, Maximize2, Minimize2, HelpCircle, UserCheck,
  Building, MapPinned, CreditCard, DollarSign, Percent, Hash,
  Link2, Unlock, LockKeyhole, BadgeCheck, Certificate, Award,
  Thermometer, Droplets, Leaf, Recycle, Wind, Sun, Battery,
  Heart, Stethoscope, Pill, Syringe, TestTubes, Microscope,
  Car, Plane, Ship, Train, Bike, Rocket,
  Coffee, Wheat, Apple, Fish, Beef, Milk, Egg,
  Shirt, Gem, Hammer, Wrench, Paintbrush,
  BookOpen, GraduationCap, Briefcase, Handshake,
  ChevronLeft, MoreVertical, Copy, Share2, Printer,
  Upload, FolderOpen, Archive, Tag, Tags,
  Camera, Mic, Video, FileUp, Image,
  Key, EyeOff, UserPlus, UserMinus,
  ThumbsUp, ThumbsDown, Flag, Bookmark,
  RotateCcw, History, Clock4,
  LayoutGrid, List, Kanban, Table2,
  ScanLine, Radar, Satellite, Telescope,
  Terminal, Code, Brackets, FileCode,
  Layers, Box, PackageOpen, ShoppingCart,
  Receipt, Invoice, Calculator, Abacus,
  FolderTree, Network, GitFork, Workflow,
  FileSearch, FileDiff, FileSignature,
  BadgeDollarSign, Banknote, Coins, PiggyBank,
  TrendingDown as Declining, ArrowUpRight, ArrowDownRight,
  CircleDot, Circle, Check, XCircle,
  Menu, PanelLeftClose, PanelLeftOpen,
  LayoutDashboard, DatabaseZap, ShieldAlert, CalendarCheck,
  FileBarChart, MessageCircle, AtSign, Globe2,
  TreePine, Leaf as EcoLeaf, Recycle as RecycleIcon,
  UserCog, Wrench as SettingsIcon, ScrollText,
  ClipboardList, ClipboardType, ClipboardX,
  LockClosed, UnlockClosed, Fingerprint as Biometric,
  Eye as ViewIcon, EyeOff as HideIcon,
  ChevronFirst, ChevronLast,
  SkipBack, SkipForward, FastForward, Rewind,
  ZoomIn, ZoomOut, Maximize, Minimize,
  GripVertical, Move, Pin, Unpin,
  Archive as ArchiveIcon, Inbox, Send as ExportIcon,
  Import, FileInput, FileOutput,
  AlertOctagon, Bug, Virus, ShieldOff,
  Ban, StopCircle, XOctagon,
  Timer, TimerReset, Hourglass,
  Sunrise, Sunset, Moon, CloudSun,
  Snowflake as Cold, Flame as Hot,
  BatteryFull, BatteryMedium, BatteryLow,
  Signal, SignalHigh, SignalLow, SignalZero,
  Wifi as Connected, WifiOff as Disconnected,
  Bluetooth, Usb, HardDrive, SdCard,
  Monitor, Smartphone, Tablet, Watch,
  Headphones, Speaker, Volume2, VolumeX,
  MicOff, VideoOff, CameraOff,
  MousePointer, Touchpad, Keyboard,
  PenTool, Highlighter, Eraser,
  Palette, Brush, Bucket,
  Scissors, Ruler, Compass,
  Type, AlignLeft, AlignCenter, AlignRight,
  Bold, Italic, Underline, Strikethrough,
  ListOrdered, ListChecks, Indent, Outdent,
  Quote, Code2, Heading1, Heading2,
  Minus as RemoveIcon, Plus as AddIcon,
  Separator, Slash, Backspace,
  Equal, Hash as NumberIcon,
  Calculator as MathIcon,
  Binary, Hexagon, Pentagon, Octagon,
  Circle as ShapeCircle, Square, Triangle,
  Sparkles, Wand2, MagicWand,
  PartyPopper, Confetti, Gift,
  Medal, Trophy, Crown, Gem as Diamond,
  Heart as Like, HeartOff as Unlike,
  ThumbUp, ThumbDown,
  Smile, Frown, Meh, Laugh,
  Angry, Sad, Surprised,
  Sun as LightMode, Moon as DarkMode,
  Monitor as SystemMode, Tablet as TabletMode,
  Smartphone as MobileMode,
  Languages, Globe as WorldIcon,
  Map as MapIcon, Navigation,
  Compass as Direction,
  Footprints, Route,
  Signpost, TrafficCone,
  Building as Office, Home, Store,
  Warehouse, School, Hospital,
  Church, Landmark,
  Mountain, Trees, Flower, Flower2,
  Waves, CloudRain, Umbrella,
  Tent, Campfire,
  Dumbbell, Bike as Bicycle, Skateboarding,
  SkiLift, Parachute,
  Music, Disc, Radio as RadioIcon,
  Tv, Gamepad2,
  Coffee as Drink, UtensilsCrossed,
  Pizza, Burger, Croissant,
  IceCream, Candy, Lollipop,
  Baby, Children, Users as Group,
  User as PersonIcon, UserCircle,
  IdCard, Passkey,
  HandMetal, Hand,
  WaveHand, Salute,
  Pointer as ClickIcon,
  Move3d, FlipHorizontal2, FlipVertical2,
  RotateCw, RotateCcw,
  Expand, Shrink,
  Fullscreen, ExitFullscreen,
  PictureInPicture2,
  SplitSquareHorizontal, SplitSquareVertical,
  Rows, Columns,
  Grid3x3, Grid2x2, Grid4x4,
  AppWindow, AppWindowSidebar,
  Browser, Chrome, Safari,
  FileJson, FileSpreadsheet, FileImage,
  FileVideo, FileAudio, FileArchive,
  Zip, Rar, Tar,
  DownloadCloud, UploadCloud,
  Share, Share2 as SocialShare,
  QrCode, Barcode,
  ScanBarcode, ScanFace,
  Camera as CameraIcon,
  Webcam, Aperture,
  ImagePlus, ImageMinus,
  Crop, Filters,
  Adjustments, SlidersHorizontal,
  ToggleLeft, ToggleRight,
  SwitchCamera, CameraRotate,
  Mic as RecordIcon,
  ScreenRecord,
  Pause as PauseIcon,
  Square as StopIcon,
  CirclePlay as PlayIcon,
  SkipBack as PrevIcon,
  SkipForward as NextIcon,
  Repeat, Repeat1, Shuffle,
  Volume1 as VolumeLow,
  Subtitles, Captions,
  Cast, Chromecast,
  Airplay, BluetoothStreaming,
  Headphones as HeadsetIcon,
  Speaker as SpeakerIcon,
} from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Progress } from '@/components/ui/progress'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Label } from '@/components/ui/label'
import { Switch } from '@/components/ui/switch'
import { Slider } from '@/components/ui/slider'
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip'
import { Toaster } from '@/components/ui/toaster'
import {
  AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip as RechartsTooltip,
  ResponsiveContainer, LineChart, Line, BarChart, Bar, PieChart, Pie, Cell,
  RadarChart, Radar, PolarGrid, PolarAngleAxis, PolarRadiusAxis,
  Legend, ScatterChart, Scatter, ComposedChart, Treemap
} from 'recharts'

// ============== TYPES & INTERFACES ==============

interface Supplier {
  id: string
  companyName: string
  registrationNumber: string
  legalEntityName: string
  dunsNumber: string
  taxId: string
  address: string
  city: string
  stateProvince: string
  postalCode: string
  country: string
  region: string
  tier: string
  category: string
  subcategory: string
  products: string[]
  certifications: string[]
  esgScore: number
  uflpaStatus: string
  eudrStatus: string
  csdddStatus: string
  soxCompliant: boolean
  gdprCompliant: boolean
  reachCompliant: boolean
  financialRating: string
  revenue: number
  employeeCount: number
  foundedYear: number
  deliveryPerformance: number
  qualityMetrics: number
  costCompetitiveness: number
  innovationScore: number
  riskLevel: 'low' | 'medium' | 'high' | 'critical'
  riskScore: number
  primaryContactName: string
  primaryContactEmail: string
  primaryContactPhone: string
  secondaryContactName: string
  secondaryContactEmail: string
  website: string
  lastAuditDate: string
  nextAuditDate: string
  contractExpiry: string
  paymentTerms: string
  currency: string
  leadTimeDays: number
  moq: number
  capacityUtilization: number
  businessContinuityPlan: boolean
  insuranceCoverage: string
  sustainabilityCertifications: string[]
  carbonFootprint: number
  waterUsage: number
  wasteReduction: number
  diversityInclusion: number
  dataPrivacyCertified: boolean
  cybersecurityRating: string
  lastUpdated: string
  notes: string
  tags: string[]
  status: 'active' | 'inactive' | 'under-review' | 'suspended'
}

interface RiskAlert {
  id: string
  type: 'geopolitical' | 'financial' | 'operational' | 'compliance' | 'environmental' | 'cybersecurity'
  severity: 'info' | 'warning' | 'critical'
  title: string
  description: string
  supplier: string
  region: string
  timestamp: string
  status: 'active' | 'investigating' | 'resolved' | 'dismissed'
  impact: string
  probability: number
  mitigation: string
  shapValues?: { feature: string; value: number; color: string }[]
}

interface ChatMessage {
  id: string
  role: 'user' | 'assistant'
  content: string
  timestamp: Date
  portal: string
}

interface ComplianceItem {
  framework: string
  status: 'compliant' | 'partial' | 'non-compliant' | 'pending-review' | 'exempt'
  score: number
  lastAssessed: string
  nextReview: string
  requirements: { name: string; status: boolean; description: string; evidence?: string }[]
  documents: { name: string; type: string; uploaded: string; verified: boolean }[]
  findings: { severity: string; description: string; remediation: string; deadline: string }[]
  owner: string
  notes: string
}

// ============== MOCK DATA ==============

const suppliersData: Supplier[] = [
  {
    id: 'SUP-001',
    companyName: 'TechComponents Global Ltd.',
    registrationNumber: 'TCG-2024-88421',
    legalEntityName: 'TechComponents Global Limited',
    dunsNumber: '36-123-4567',
    taxId: 'GB123456789012',
    address: '100 Innovation Drive',
    city: 'Cambridge',
    stateProvince: 'Cambridgeshire',
    postalCode: 'CB1 2AZ',
    country: 'United Kingdom',
    region: 'Europe',
    tier: 'Tier 1',
    category: 'Electronics Manufacturing',
    subcategory: 'Semiconductor Components',
    products: ['Microcontrollers', 'Memory Chips', 'Sensors', 'Power Management ICs'],
    certifications: ['ISO 9001', 'ISO 14001', 'ISO 27001', 'AS9100D', 'IATF 16949'],
    esgScore: 87,
    uflpaStatus: 'Compliant',
    eudrStatus: 'N/A - Non-Forestry',
    csdddStatus: 'Compliant',
    soxCompliant: true,
    gdprCompliant: true,
    reachCompliant: true,
    financialRating: 'AA',
    revenue: 2450000000,
    employeeCount: 12500,
    foundedYear: 1987,
    deliveryPerformance: 96.8,
    qualityMetrics: 99.2,
    costCompetitiveness: 82,
    innovationScore: 91,
    riskLevel: 'low',
    riskScore: 12,
    primaryContactName: 'Sarah Mitchell',
    primaryContactEmail: 's.mitchell@techcomponents.com',
    primaryContactPhone: '+44 1223 5550101',
    secondaryContactName: 'James Chen',
    secondaryContactEmail: 'j.chen@techcomponents.com',
    website: 'https://www.techcomponents.com',
    lastAuditDate: '2024-11-15',
    nextAuditDate: '2025-05-15',
    contractExpiry: '2026-12-31',
    paymentTerms: 'Net 60',
    currency: 'GBP',
    leadTimeDays: 14,
    moq: 5000,
    capacityUtilization: 78,
    businessContinuityPlan: true,
    insuranceCoverage: '$50M Comprehensive Liability',
    sustainabilityCertifications: ['EcoVadis Platinum', 'Science Based Targets'],
    carbonFootprint: 12400,
    waterUsage: 89000,
    wasteReduction: 34,
    diversityInclusion: 78,
    dataPrivacyCertified: true,
    cybersecurityRating: 'A+',
    lastUpdated: '2025-01-20',
    notes: 'Strategic partner since 2019. Excellent track record. Expanding capacity in 2025.',
    tags: ['strategic', 'electronics', 'semiconductors', 'ESG-leader'],
    status: 'active'
  },
  {
    id: 'SUP-002',
    companyName: 'Pacific Precision Industries',
    registrationNumber: 'PPI-TW-99234',
    legalEntityName: 'Pacific Precision Industries Co., Ltd.',
    dunsNumber: '88-456-7890',
    taxId: 'TW987654321098',
    address: 'No. 88, Sec. 1, Hsin Tai Wu Road',
    city: 'Hsinchu',
    stateProvince: 'Hsinchu County',
    postalCode: '300',
    country: 'Taiwan',
    region: 'Asia Pacific',
    tier: 'Tier 1',
    category: 'Precision Manufacturing',
    subcategory: 'Optical Components',
    products: ['Lens Assemblies', 'Prisms', 'Filters', 'Optical Sensors'],
    certifications: ['ISO 9001', 'ISO 14001', 'ISO 45001'],
    esgScore: 76,
    uflpaStatus: 'Under Review',
    eudrStatus: 'N/A - Non-Forestry',
    csdddStatus: 'Pending Assessment',
    soxCompliant: false,
    gdprCompliant: false,
    reachCompliant: false,
    financialRating: 'A+',
    revenue: 1800000000,
    employeeCount: 8900,
    foundedYear: 1995,
    deliveryPerformance: 94.2,
    qualityMetrics: 97.8,
    costCompetitiveness: 88,
    innovationScore: 85,
    riskLevel: 'medium',
    riskScore: 35,
    primaryContactName: 'Wei-Lin Huang',
    primaryContactEmail: 'wl.huang@pacificprecision.tw',
    primaryContactPhone: '+886 3 567 8901',
    secondaryContactName: 'Mei Lin Tsai',
    secondaryContactEmail: 'ml.tsai@pacificprecision.tw',
    website: 'https://www.pacificprecision.com.tw',
    lastAuditDate: '2024-08-22',
    nextAuditDate: '2025-02-22',
    contractExpiry: '2025-09-30',
    paymentTerms: 'Net 45',
    currency: 'TWD',
    leadTimeDays: 21,
    moq: 10000,
    capacityUtilization: 85,
    businessContinuityPlan: true,
    insuranceCoverage: '$30M Product Liability',
    sustainabilityCertifications: ['EcoVadis Gold'],
    carbonFootprint: 18900,
    waterUsage: 145000,
    wasteReduction: 28,
    diversityInclusion: 65,
    dataPrivacyCertified: false,
    cybersecurityRating: 'B+',
    lastUpdated: '2025-01-18',
    notes: 'UFLPA review in progress due to Xinjiang-sourced raw materials claim. Monitoring closely.',
    tags: ['optics', 'taiwan', 'precision', 'UFLPA-watch'],
    status: 'under-review'
  },
  {
    id: 'SUP-003',
    companyName: 'EuroChem Solutions GmbH',
    registrationNumber: 'HRB-DE-45678',
    legalEntityName: 'EuroChem Solutions Gesellschaft mit beschränkter Haftung',
    dunsNumber: '52-789-0123',
    taxId: 'DE234567890123',
    address: 'Industriestraße 42',
    city: 'Ludwigshafen',
    stateProvince: 'Rhineland-Palatinate',
    postalCode: '67063',
    country: 'Germany',
    region: 'Europe',
    tier: 'Tier 2',
    category: 'Chemicals',
    subcategory: 'Specialty Chemicals',
    products: ['Polymer Additives', 'Coating Agents', 'Adhesives', 'Sealants'],
    certifications: ['ISO 9001', 'ISO 14001', 'REACH Registered', 'ISO 45001'],
    esgScore: 82,
    uflpaStatus: 'Compliant',
    eudrStatus: 'Compliant',
    csdddStatus: 'Compliant',
    soxCompliant: true,
    gdprCompliant: true,
    reachCompliant: true,
    financialRating: 'A',
    revenue: 980000000,
    employeeCount: 4200,
    foundedYear: 1962,
    deliveryPerformance: 92.5,
    qualityMetrics: 98.5,
    costCompetitiveness: 75,
    innovationScore: 79,
    riskLevel: 'low',
    riskScore: 18,
    primaryContactName: 'Dr. Klaus Weber',
    primaryContactEmail: 'k.weber@eurochem.de',
    primaryContactPhone: '+49 621 5550345',
    secondaryContactName: 'Anna Schmidt',
    secondaryContactEmail: 'a.schmidt@eurochem.de',
    website: 'https://www.eurochem-solutions.de',
    lastAuditDate: '2024-10-05',
    nextAuditDate: '2025-04-05',
    contractExpiry: '2027-06-30',
    paymentTerms: 'Net 30',
    currency: 'EUR',
    leadTimeDays: 10,
    moq: 2000,
    capacityUtilization: 72,
    businessContinuityPlan: true,
    insuranceCoverage: '$75M Environmental + Liability',
    sustainabilityCertifications: ['EcoVadis Platinum', 'EU Ecolabel', 'Blue Angel'],
    carbonFootprint: 28000,
    waterUsage: 210000,
    wasteReduction: 45,
    diversityInclusion: 82,
    dataPrivacyCertified: true,
    cybersecurityRating: 'A',
    lastUpdated: '2025-01-22',
    notes: 'Strong ESG performer. Leading REACH compliance. Expanding bio-based product line.',
    tags: ['chemicals', 'germany', 'ESG-leader', 'REACH-expert'],
    status: 'active'
  },
  {
    id: 'SUP-004',
    companyName: 'Shanghai Advanced Materials Co.',
    registrationNumber: 'SHAM-CN-11223',
    legalEntityName: 'Shanghai Advanced Materials Co., Ltd.',
    dunsNumber: '91-234-5678',
    taxId: 'CN91234567890123',
    address: '888 Zhangjiang High-Tech Park Road',
    city: 'Shanghai',
    stateProvince: 'Shanghai Municipality',
    postalCode: '201203',
    country: 'China',
    region: 'Asia Pacific',
    tier: 'Tier 1',
    category: 'Advanced Materials',
    subcategory: 'Composite Materials',
    products: ['Carbon Fiber Prepregs', 'Ceramic Matrix Composites', 'Metal Matrix Composites'],
    certifications: ['ISO 9001', 'ISO 14001', 'AS9100D'],
    esgScore: 68,
    uflpaStatus: 'High Risk',
    eudrStatus: 'N/A - Non-Forestry',
    csdddStatus: 'Non-Compliant',
    soxCompliant: false,
    gdprCompliant: false,
    reachCompliant: false,
    financialRating: 'BBB+',
    revenue: 3200000000,
    employeeCount: 18500,
    foundedYear: 2003,
    deliveryPerformance: 89.5,
    qualityMetrics: 95.2,
    costCompetitiveness: 94,
    innovationScore: 88,
    riskLevel: 'high',
    riskScore: 62,
    primaryContactName: 'Li Wei Zhang',
    primaryContactEmail: 'lw.zhang@shamaterials.cn',
    primaryContactPhone: '+86 21 5550 7890',
    secondaryContactName: 'Ying Liu',
    secondaryContactEmail: 'ying.liu@shamaterials.cn',
    website: 'http://www.shamaterials.cn',
    lastAuditDate: '2024-06-18',
    nextAuditDate: '2025-01-18',
    contractExpiry: '2025-12-31',
    paymentTerms: 'Net 90',
    currency: 'CNY',
    leadTimeDays: 35,
    moq: 25000,
    capacityUtilization: 92,
    businessContinuityPlan: false,
    insuranceCoverage: '$20M Basic Liability',
    sustainabilityCertifications: [],
    carbonFootprint: 45000,
    waterUsage: 380000,
    wasteReduction: 15,
    diversityInclusion: 45,
    dataPrivacyCertified: false,
    cybersecurityRating: 'C',
    lastUpdated: '2025-01-15',
    notes: 'CRITICAL: UFLPA high-risk due to suspected Xinjiang labor. CSDDD non-compliant. Alternative sourcing required by Q2 2025.',
    tags: ['materials', 'china', 'HIGH-RISK', 'UFLPA-critical', 'CSDDD-issue'],
    status: 'under-review'
  },
  {
    id: 'SUP-005',
    companyName: 'Americas Logistics Partners LLC',
    registrationNumber: 'ALP-US-55667',
    legalEntityName: 'Americas Logistics Partners, LLC',
    dunsNumber: '12-345-6789',
    taxId: 'US987654321098',
    address: '1500 Logistics Way, Suite 400',
    city: 'Chicago',
    stateProvince: 'Illinois',
    postalCode: '60601',
    country: 'United States',
    region: 'North America',
    tier: 'Tier 2',
    category: 'Logistics & Distribution',
    subcategory: 'Freight Forwarding',
    products: ['Ocean Freight', 'Air Freight', 'Warehousing', 'Last-Mile Delivery'],
    certifications: ['ISO 9001', 'ISO 14001', 'C-TPAT', 'AEO Certified'],
    esgScore: 74,
    uflpaStatus: 'Compliant',
    eudrStatus: 'N/A - Non-Forestry',
    csdddStatus: 'Partial Compliance',
    soxCompliant: true,
    gdprCompliant: true,
    reachCompliant: false,
    financialRating: 'A-',
    revenue: 1500000000,
    employeeCount: 7800,
    foundedYear: 2001,
    deliveryPerformance: 93.8,
    qualityMetrics: 96.5,
    costCompetitiveness: 80,
    innovationScore: 72,
    riskLevel: 'low',
    riskScore: 22,
    primaryContactName: 'Michael Rodriguez',
    primaryContactEmail: 'm.rodriguez@americaslogistics.com',
    primaryContactPhone: '+1 312 555 0199',
    secondaryContactName: 'Jennifer Adams',
    secondaryContactEmail: 'j.adams@americaslogistics.com',
    website: 'https://www.americaslogistics.com',
    lastAuditDate: '2024-09-10',
    nextAuditDate: '2025-03-10',
    contractExpiry: '2026-06-30',
    paymentTerms: 'Net 45',
    currency: 'USD',
    leadTimeDays: 3,
    moq: 1,
    capacityUtilization: 68,
    businessContinuityPlan: true,
    insuranceCoverage: '$100M Cargo + Liability',
    sustainabilityCertifications: ['Smartway Partner', 'EcoVadis Silver'],
    carbonFootprint: 52000,
    waterUsage: 12000,
    wasteReduction: 22,
    diversityInclusion: 85,
    dataPrivacyCertified: true,
    cybersecurityRating: 'A-',
    lastUpdated: '2025-01-21',
    notes: 'Reliable logistics partner. Fleet electrification program underway. Good geographic coverage.',
    tags: ['logistics', 'usa', 'freight', 'sustainability'],
    status: 'active'
  },
  {
    id: 'SUP-006',
    companyName: 'Nordic Renewable Energy AB',
    registrationNumber: 'NRE-SE-77889',
    legalEntityName: 'Nordic Renewable Energy Aktiebolag',
    dunsNumber: '65-678-9012',
    taxId: 'SE556789012345',
    address: 'Storgatan 15',
    city: 'Stockholm',
    stateProvince: 'Stockholm County',
    postalCode: '111 43',
    country: 'Sweden',
    region: 'Europe',
    tier: 'Tier 2',
    category: 'Renewable Energy',
    subcategory: 'Wind Turbine Components',
    products: ['Rotor Blades', 'Gearboxes', 'Generators', 'Control Systems'],
    certifications: ['ISO 9001', 'ISO 14001', 'ISO 45001', 'ISO 50001'],
    esgScore: 94,
    uflpaStatus: 'Compliant',
    eudrStatus: 'Compliant',
    csdddStatus: 'Compliant',
    soxCompliant: true,
    gdprCompliant: true,
    reachCompliant: true,
    financialRating: 'AA-',
    revenue: 420000000,
    employeeCount: 2300,
    foundedYear: 2008,
    deliveryPerformance: 91.2,
    qualityMetrics: 97.5,
    costCompetitiveness: 70,
    innovationScore: 95,
    riskLevel: 'low',
    riskScore: 8,
    primaryContactName: 'Erik Lindqvist',
    primaryContactEmail: 'e.lindqvist@nordicrenewable.se',
    primaryContactPhone: '+46 8 555 1234',
    secondaryContactName: 'Sofia Andersson',
    secondaryContactEmail: 's.andersson@nordicrenewable.se',
    website: 'https://www.nordicrenewable.se',
    lastAuditDate: '2024-12-01',
    nextAuditDate: '2025-06-01',
    contractExpiry: '2028-12-31',
    paymentTerms: 'Net 60',
    currency: 'SEK',
    leadTimeDays: 28,
    moq: 50,
    capacityUtilization: 88,
    businessContinuityPlan: true,
    insuranceCoverage: '$40M Product + Environmental',
    sustainabilityCertifications: ['EcoVadis Platinum', 'B Corp Certified', 'Climate Neutral'],
    carbonFootprint: 8500,
    waterUsage: 25000,
    wasteReduction: 58,
    diversityInclusion: 91,
    dataPrivacyCertified: true,
    cybersecurityRating: 'A+',
    lastUpdated: '2025-01-24',
    notes: 'Industry-leading ESG performance. Carbon neutral operations. Premium pricing justified by quality.',
    tags: ['renewable', 'sweden', 'ESG-champion', 'wind-energy', 'B-Corp'],
    status: 'active'
  },
  {
    id: 'SUP-007',
    companyName: 'IndiaTech Manufacturing Pvt. Ltd.',
    registrationNumber: 'ITM-IN-33445',
    legalEntityName: 'IndiaTech Manufacturing Private Limited',
    dunsNumber: '74-890-1234',
    taxId: 'IN345678901234',
    address: 'PEEC Phase II, Plot No. 45',
    city: 'Pune',
    stateProvince: 'Maharashtra',
    postalCode: '411057',
    country: 'India',
    region: 'Asia Pacific',
    tier: 'Tier 2',
    category: 'Electronics Assembly',
    subcategory: 'PCBA Manufacturing',
    products: ['PCB Assembly', 'Box Build', 'Cable Harnesses', 'Testing Services'],
    certifications: ['ISO 9001', 'ISO 14001', 'IPC-A-610 Class 3'],
    esgScore: 71,
    uflpaStatus: 'Compliant',
    eudrStatus: 'N/A - Non-Forestry',
    csdddStatus: 'Pending Assessment',
    soxCompliant: false,
    gdprCompliant: false,
    reachCompliant: false,
    financialRating: 'BBB',
    revenue: 650000000,
    employeeCount: 5500,
    foundedYear: 2010,
    deliveryPerformance: 88.5,
    qualityMetrics: 94.8,
    costCompetitiveness: 91,
    innovationScore: 76,
    riskLevel: 'medium',
    riskScore: 38,
    primaryContactName: 'Rajesh Kumar',
    primaryContactEmail: 'r.kumar@indiatech.in',
    primaryContactPhone: '+91 20 555 6789',
    secondaryContactName: 'Priya Sharma',
    secondaryContactEmail: 'p.sharma@indiatech.in',
    website: 'https://www.indiatech.co.in',
    lastAuditDate: '2024-07-20',
    nextAuditDate: '2025-01-20',
    contractExpiry: '2025-08-31',
    paymentTerms: 'Net 60',
    currency: 'INR',
    leadTimeDays: 18,
    moq: 5000,
    capacityUtilization: 82,
    businessContinuityPlan: true,
    insuranceCoverage: '$25M Product Liability',
    sustainabilityCertifications: ['EcoVadis Bronze'],
    carbonFootprint: 22000,
    waterUsage: 175000,
    wasteReduction: 20,
    diversityInclusion: 72,
    dataPrivacyCertified: false,
    cybersecurityRating: 'B',
    lastUpdated: '2025-01-17',
    notes: 'Cost-effective assembly partner. Quality improving steadily. CSDDD assessment scheduled for Q1 2025.',
    tags: ['assembly', 'india', 'cost-effective', 'electronics'],
    status: 'active'
  },
  {
    id: 'SUP-008',
    companyName: 'BrazilAgro Commodities SA',
    registrationNumber: 'BAG-BR-66778',
    legalEntityName: 'BrazilAgro Commodidades Sociedade Anônima',
    dunsNumber: '38-901-2345',
    taxId: 'BR45678901234567',
    address: 'Avenida Paulista, 1106',
    city: 'São Paulo',
    stateProvince: 'São Paulo State',
    postalCode: '01310-100',
    country: 'Brazil',
    region: 'Latin America',
    tier: 'Tier 2',
    category: 'Agriculture & Forestry',
    subcategory: 'Soy & Palm Oil',
    products: ['Soybeans', 'Palm Oil', 'Coffee Beans', 'Sugar'],
    certifications: ['ISO 9001', 'RSPO', 'RTRS', 'Rainforest Alliance'],
    esgScore: 64,
    uflpaStatus: 'Compliant',
    eudrStatus: 'Under Review',
    csdddStatus: 'Non-Compliant',
    soxCompliant: false,
    gdprCompliant: false,
    reachCompliant: false,
    financialRating: 'BB+',
    revenue: 2800000000,
    employeeCount: 12500,
    foundedYear: 1955,
    deliveryPerformance: 85.2,
    qualityMetrics: 92.5,
    costCompetitiveness: 86,
    innovationScore: 58,
    riskLevel: 'high',
    riskScore: 55,
    primaryContactName: 'Carlos Silva',
    primaryContactEmail: 'c.silva@brazilagro.br',
    primaryContactPhone: '+55 11 5555 0123',
    secondaryContactName: 'Maria Oliveira',
    secondaryContactEmail: 'm.oliveira@brazilagro.br',
    website: 'https://www.brazilagro.com.br',
    lastAuditDate: '2024-05-12',
    nextAuditDate: '2024-11-12',
    contractExpiry: '2025-06-30',
    paymentTerms: 'Net 90',
    currency: 'BRL',
    leadTimeDays: 45,
    moq: 100000,
    capacityUtilization: 95,
    businessContinuityPlan: false,
    insuranceCoverage: '$35M Agricultural + Liability',
    sustainabilityCertifications: ['RSPO Certified', 'RTRS Member'],
    carbonFootprint: 78000,
    waterUsage: 1200000,
    wasteReduction: 12,
    diversityInclusion: 68,
    dataPrivacyCertified: false,
    cybersecurityRating: 'C-',
    lastUpdated: '2025-01-14',
    notes: 'EUDR under review due to Amazon deforestation concerns. Deforestation-free sourcing verification pending. HIGH ATTENTION REQUIRED.',
    tags: ['agriculture', 'brazil', 'EUDR-watch', 'deforestation-risk', 'commodities'],
    status: 'under-review'
  },
  {
    id: 'SUP-009',
    companyName: 'JapanAuto Parts KK',
    registrationNumber: 'JAP-JP-88990',
    legalEntityName: 'JapanAuto Parts Kabushiki Kaisha',
    dunsNumber: '47-012-3456',
    taxId: 'JP5678901234567',
    address: '1-2-3 Toyota-cho',
    city: 'Toyota',
    stateProvince: 'Aichi Prefecture',
    postalCode: '471-0806',
    country: 'Japan',
    region: 'Asia Pacific',
    tier: 'Tier 1',
    category: 'Automotive Components',
    subcategory: 'Powertrain Systems',
    products: ['Transmission Systems', 'Engine Components', 'Hybrid Systems', 'EV Powertrains'],
    certifications: ['ISO 9001', 'IATF 16949', 'ISO 14001', 'ISO 27001'],
    esgScore: 86,
    uflpaStatus: 'Compliant',
    eudrStatus: 'N/A - Non-Forestry',
    csdddStatus: 'Compliant',
    soxCompliant: true,
    gdprCompliant: true,
    reachCompliant: true,
    financialRating: 'AAA',
    revenue: 5800000000,
    employeeCount: 28000,
    foundedYear: 1948,
    deliveryPerformance: 98.2,
    qualityMetrics: 99.5,
    costCompetitiveness: 78,
    innovationScore: 93,
    riskLevel: 'low',
    riskScore: 5,
    primaryContactName: 'Takeshi Yamamoto',
    primaryContactEmail: 't.yamamoto@japanautoparts.jp',
    primaryContactPhone: '+81 565 55 1234',
    secondaryContactName: 'Yuki Tanaka',
    secondaryContactEmail: 'y.tanaka@japanautoparts.jp',
    website: 'https://www.japanautoparts.co.jp',
    lastAuditDate: '2024-11-28',
    nextAuditDate: '2025-05-28',
    contractExpiry: '2029-12-31',
    paymentTerms: 'Net 30',
    currency: 'JPY',
    leadTimeDays: 8,
    moq: 1000,
    capacityUtilization: 76,
    businessContinuityPlan: true,
    insuranceCoverage: '$200M Comprehensive',
    sustainabilityCertifications: ['EcoVadis Platinum', 'Carbon Neutral 2030 Pledge'],
    carbonFootprint: 35000,
    waterUsage: 95000,
    wasteRedolution: 48,
    diversityInclusion: 75,
    dataPrivacyCertified: true,
    cybersecurityRating: 'A+',
    lastUpdated: '2025-01-23',
    notes: 'World-class automotive supplier. Zero defect target achieved 3 consecutive years. EV transition leader.',
    tags: ['automotive', 'japan', 'tier-1', 'world-class', 'EV-ready'],
    status: 'active'
  },
  {
    id: 'SUP-010',
    companyName: 'VietnamTextile Group JSC',
    registrationNumber: 'VTG-VN-00112',
    legalEntityName: 'VietnamTextile Group Joint Stock Company',
    dunsNumber: '83-123-4567',
    taxId: 'VN0123456789',
    address: 'Lot A3, VSIP II Industrial Park',
    city: 'Binh Duong',
    stateProvince: 'Binh Duong Province',
    postalCode: '800000',
    country: 'Vietnam',
    region: 'Asia Pacific',
    tier: 'Tier 3',
    category: 'Textiles & Apparel',
    subcategory: 'Garment Manufacturing',
    products: ['Workwear Uniforms', 'Casual Apparel', 'Technical Textiles', 'Protective Clothing'],
    certifications: ['ISO 9001', 'ISO 14001', 'WRAP Certified', 'OEKO-TEX Standard 100'],
    esgScore: 59,
    uflpaStatus: 'Under Review',
    eudrStatus: 'N/A - Non-Forestry',
    csdddStatus: 'Non-Compliant',
    soxCompliant: false,
    gdprCompliant: false,
    reachCompliant: false,
    financialRating: 'BB-',
    revenue: 380000000,
    employeeCount: 15000,
    foundedYear: 2005,
    deliveryPerformance: 84.5,
    qualityMetrics: 91.2,
    costCompetitiveness: 95,
    innovationScore: 52,
    riskLevel: 'high',
    riskScore: 58,
    primaryContactName: 'Nguyen Van Minh',
    primaryContactEmail: 'nv.minh@vietnamtextile.vn',
    primaryContactPhone: '+84 274 555 6789',
    secondaryContactName: 'Tran Thi Hoa',
    secondaryContactEmail: 'tt.hoa@vietnamtextile.vn',
    website: 'https://www.vietnamtextile.vn',
    lastAuditDate: '2024-04-15',
    nextAuditDate: '2024-10-15',
    contractExpiry: '2025-03-31',
    paymentTerms: 'Net 60',
    currency: 'VND',
    leadTimeDays: 42,
    moq: 50000,
    capacityUtilization: 94,
    businessContinuityPlan: false,
    insuranceCoverage: '$15M Basic Liability',
    sustainabilityCertifications: ['WRAP Certified'],
    carbonFootprint: 32000,
    waterUsage: 450000,
    wasteReduction: 18,
    diversityInclusion: 62,
    dataPrivacyCertified: false,
    cybersecurityRating: 'D',
    lastUpdated: '2025-01-12',
    notes: 'Labor practices under scrutiny. UFLPA review ongoing due to supply chain transparency issues. Consider diversification.',
    tags: ['textiles', 'vietnam', 'labor-concerns', 'cost-leader', 'tier-3'],
    status: 'under-review'
  }
]

const alertsData: RiskAlert[] = [
  {
    id: 'ALT-001',
    type: 'compliance',
    severity: 'critical',
    title: 'UFLPA Entity List Match Detected',
    description: 'Shanghai Advanced Materials has been flagged for potential connection to entities on the UFLPA Entity List. Immediate investigation required.',
    supplier: 'Shanghai Advanced Materials Co.',
    region: 'Asia Pacific',
    timestamp: '2025-01-24T14:32:00Z',
    status: 'active',
    impact: 'Supply disruption, customs detention, reputational damage',
    probability: 85,
    mitigation: 'Engage third-party audit firm for supply chain traceability verification within 14 days',
    shapValues: [
      { feature: 'Geographic Risk Score', value: 0.35, color: '#ef4444' },
      { feature: 'Entity Connection Strength', value: 0.28, color: '#f97316' },
      { feature: 'Raw Material Origin', value: 0.22, color: '#eab308' },
      { feature: 'Transparency Score', value: 0.12, color: '#22c55e' },
      { feature: 'Historical Compliance', value: 0.03, color: '#3b82f6' }
    ]
  },
  {
    id: 'ALT-002',
    type: 'environmental',
    severity: 'warning',
    title: 'EUDR Deforestation Risk Identified',
    description: 'BrazilAgro Commodities\' soy sourcing area shows satellite-detected deforestation activity within restricted zones.',
    supplier: 'BrazilAgro Commodities SA',
    region: 'Latin America',
    timestamp: '2025-01-24T11:15:00Z',
    status: 'active',
    impact: 'Market access restriction in EU, customer rejection, fines up to 4% EU turnover',
    probability: 72,
    mitigation: 'Request geolocation data for all sourcing areas. Engage satellite monitoring service.',
    shapValues: [
      { feature: 'Satellite Detection Confidence', value: 0.42, color: '#ef4444' },
      { feature: 'Sourcing Proximity to Protected Area', value: 0.25, color: '#f97316' },
      { feature: 'Supplier Traceability Score', value: 0.18, color: '#eab308' },
      { feature: 'Certification Coverage', value: 0.10, color: '#22c55e' },
      { feature: 'Historical Incidents', value: 0.05, color: '#3b82f6' }
    ]
  },
  {
    id: 'ALT-003',
    type: 'financial',
    severity: 'warning',
    title: 'Credit Rating Downgrade Warning',
    description: 'VietnamTextile Group credit outlook revised to negative by Moody\'s due to declining margins and high leverage.',
    supplier: 'VietnamTextile Group JSC',
    region: 'Asia Pacific',
    timestamp: '2025-01-23T16:45:00Z',
    status: 'investigating',
    impact: 'Payment default risk, potential supply disruption, increased costs of alternative sourcing',
    probability: 45,
    mitigation: 'Reduce exposure by 30%. Require letter of credit for future orders. Identify backup suppliers.',
    shapValues: [
      { feature: 'Debt-to-EBITDA Ratio', value: 0.32, color: '#ef4444' },
      { feature: 'Operating Margin Trend', value: 0.26, color: '#f97316' },
      { feature: 'Cash Flow Coverage', value: 0.20, color: '#eab308' },
      { feature: 'Customer Concentration', value: 0.14, color: '#22c55e' },
      { feature: 'Industry Outlook', value: 0.08, color: '#3b82f6' }
    ]
  },
  {
    id: 'ALT-004',
    type: 'cybersecurity',
    severity: 'critical',
    title: 'Critical Vulnerability Detected in Supplier Portal',
    description: 'Shanghai Advanced Materials supplier portal exposed critical SQL injection vulnerability allowing potential data breach.',
    supplier: 'Shanghai Advanced Materials Co.',
    region: 'Asia Pacific',
    timestamp: '2025-01-24T09:20:00Z',
    status: 'active',
    impact: 'Data exfiltration risk, IP theft, regulatory notification requirements under GDPR',
    probability: 78,
    mitigation: 'Immediate portal access suspension. Mandate security assessment before reconnection.',
    shapValues: [
      { feature: 'CVSS Severity Score', value: 0.45, color: '#ef4444' },
      { feature: 'Exposed Data Sensitivity', value: 0.25, color: '#f97316' },
      { feature: 'Patch Availability', value: 0.15, color: '#eab308' },
      { feature: 'Access Control Maturity', value: 0.10, color: '#22c55e' },
      { feature: 'Incident Response Capability', value: 0.05, color: '#3b82f6' }
    ]
  },
  {
    id: 'ALT-005',
    type: 'operational',
    severity: 'info',
    title: 'Capacity Utilization Threshold Exceeded',
    description: 'BrazilAgro Commodities operating at 95% capacity. Risk of order fulfillment delays during peak season.',
    supplier: 'BrazilAgro Commodities SA',
    region: 'Latin America',
    timestamp: '2025-01-24T07:00:00Z',
    status: 'active',
    impact: 'Potential 2-3 week delivery delays, expedited shipping costs',
    probability: 65,
    mitigation: 'Pre-position safety stock. Activate secondary supplier agreements.',
    shapValues: [
      { feature: 'Current Utilization %', value: 0.40, color: '#ef4444' },
      { feature: 'Seasonal Demand Spike', value: 0.28, color: '#f97316' },
      { feature: 'Lead Time Buffer', value: 0.18, color: '#eab308' },
      { feature: 'Alternative Capacity Available', value: 0.10, color: '#22c55e' },
      { feature: 'Historical Performance', value: 0.04, color: '#3b82f6' }
    ]
  },
  {
    id: 'ALT-006',
    type: 'geopolitical',
    severity: 'warning',
    title: 'Taiwan Strait Tensions Escalation',
    description: 'Increased military activity in Taiwan Strait may affect Pacific Precision Industries shipments.',
    supplier: 'Pacific Precision Industries',
    region: 'Asia Pacific',
    timestamp: '2025-01-23T22:30:00Z',
    status: 'investigating',
    impact: 'Shipping route disruptions, insurance premium increases, potential port closures',
    probability: 35,
    mitigation: 'Evaluate air freight alternatives. Increase safety stock for critical components.',
    shapValues: [
      { feature: 'Geographic Proximity', value: 0.38, color: '#ef4444' },
      { feature: 'Shipping Route Dependency', value: 0.27, color: '#f97316' },
      { feature: 'Alternative Route Availability', value: 0.20, color: '#eab308' },
      { feature: 'Inventory Buffer Days', value: 0.10, color: '#22c55e' },
      { feature: 'Political Stability Index', value: 0.05, color: '#3b82f6' }
    ]
  }
]

const riskTrendData = [
  { month: 'Aug', overallRisk: 42, geopolitical: 35, financial: 48, operational: 38, compliance: 52, environmental: 28 },
  { month: 'Sep', overallRisk: 45, geopolitical: 40, financial: 45, operational: 42, compliance: 55, environmental: 30 },
  { month: 'Oct', overallRisk: 48, geopolitical: 45, financial: 42, operational: 45, compliance: 58, environmental: 32 },
  { month: 'Nov', overallRisk: 52, geopolitical: 52, financial: 48, operation